### PR TITLE
Add play/pause functionality.

### PR DESCRIPTION
**Pull request by kenrussell**
Rephrase the extension's functionality so that it not only plays all
audio elements or WebAudio contexts which were blocked, but can pause
and resume all of them again afterward.

Redo the icons as play and pause buttons. Remove the notification.

### CODE REVIEW

**Comment by kenrussell** [comment]
Jaume: I'm proposing these changes as a way of prototyping what the UI for this functionality might look like if it were built in to the browser.

I realize this is a large change – basically a rewrite – and it probably has bugs. I mainly tested it with https://www.shadertoy.com/view/Xds3Rr and it works there (tested on a build of Chromium which has the autoplay restrictions in place, though). I plan to continue to refine it, but there are some time constraints for getting this in other peoples' hands to look at. So if there are no strong objections to the general direction of these changes I'd appreciate being able to merge these changes in sooner rather than later.

Thanks for your consideration.

**Comment by spite** [comment]
Thanks, Ken! 

Seems to work more or less with the same sites (i've found a kongregate game that doesn't seem to work with this rewrite). 

To be honest, developing and testing this extension is being a bit tricky, considering that the policy is being discussed and that Chrome and DevTools behave inconsistently across sessions, reloads and navigation.

As long as sites that don't work can be reported and improve the mechanism to unmute media, I think it's the best that we can do at the moment.

**Comment by kenrussell** [comment]
Thanks for merging this Jaume. Would you mind sending me the link to that Kongregate game?

I know that developing this is tricky – ran into those issues myself, especially that opening DevTools makes all of the audio suddenly start working. It's down to console.log() calls and looking at them after the fact. But this is a very useful talking point and proof point, so thanks for writing it and being open to having it be a testbed.

**Comment by spite** [comment]
I mostly go through the sites in https://bugs.chromium.org/p/chromium/issues/detail?id=840866#c103

I was mistaken and it's not a kongregate game, it's armor games https://armorgames.com/play/18190/string-theory-2 (and it's a Unity game)

**Pull request merged**
